# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'e8a176d7-6486-4189-9153-5fd813a62ee8'

  # Web app name
  webAppName: 'testaz400javaapp'

  # Environment name
  environmentName: 'testaz400javaapp'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:
- template: ./test.yml