
parameters:
    azureSubscription: ''

  # Web app name
    webAppName: ''

  # Environment name
    environmentName: ''

  # Agent VM image name
    vmImageName: ''

stages:
- stage: Build
  displayName: Build stage
  jobs:
      - job: MavenPackageAndPublishArtifacts
        displayName: Maven Package and Publish Artifacts
        pool:
          vmImage: $({parameters.vmImageName})

        steps:
          - task: Maven@3
            displayName: 'Maven Package'
            inputs:
              mavenPomFile: 'pom.xml'

          - task: CopyFiles@2
            displayName: 'Copy Files to artifact staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**/target/*.?(war|jar)'
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - upload: $(Build.ArtifactStagingDirectory)
            artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
      - deployment: DeployLinuxWebApp
        displayName: Deploy Linux Web App
        environment: $({parameters.environmentName})
        pool:
          vmImage: $({parameters.vmImageName})
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Azure Web App Deploy: testaz400javaapp'
                  inputs:
                    azureSubscription: $({parameters.azureSubscription})
                    appType: webAppLinux
                    appName: $({parameters.webAppName})
                    package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
